//
//  getCountry.swift
//  birth_lottery
//
//  Created by shreya nallamothu on 4/21/26.
//
struct countryInfo{
    static let weights: [String: Double] = [
        "India": 18.024,
        "China": 17.9099,
        "United States of America": 4.2282,
        "Indonesia": 3.4962,
        "Pakistan": 3.0292,
        "Nigeria": 2.8146,
        "Brazil": 2.7262,
        "Bangladesh": 2.1835,
        "Russia": 1.8175,
        "Mexico": 1.6282,
        "Ethiopia": 1.5903,
        "Japan": 1.5651,
        "Philippines": 1.4767,
        "Egypt": 1.3253,
        "Democratic Republic of the Congo": 1.2874,
        "Viet Nam": 1.2369,
        "Iran": 1.1233,
        "Turkey": 1.0728,
        "Germany": 1.0602,
        "Thailand": 0.9087,
        "United Kingdom of Great Britain and Northern Ireland (the)": 0.8583,
        "France": 0.8583,
        "Tanzania, United Republic of": 0.8204,
        "South Africa": 0.7573,
        "Kenya": 0.6942,
        "Myanmar": 0.6816,
        "Korea": 0.6563,
        "Colombia": 0.6563,
        "Uganda": 0.6058,
        "Spain": 0.5932,
        "Sudan": 0.5806,
        "Argentina": 0.5806,
        "Algeria": 0.568,
        "Ukraine": 0.5553,
        "Afghanistan": 0.5301,
        "Iraq": 0.5301,
        "Poland": 0.5175,
        "Canada": 0.4796,
        "Morocco": 0.467,
        "Saudi Arabia": 0.4544,
        "Angola": 0.4544,
        "Uzbekistan": 0.4418,
        "Yemen": 0.4291,
        "Peru": 0.4165,
        "Malaysia": 0.4165,
        "Ghana": 0.4165,
        "Mozambique": 0.4165,
        "Nepal": 0.3786,
        "Venezuela": 0.366,
        "Madagascar": 0.3534,
        "Cameroon": 0.3534,
        "Côte d'Ivoire": 0.3408,
        "Australia": 0.3282,
        "North Korea": 0.3282,
        "Niger": 0.3282,
        "Taiwan": 0.2903,
        "Mali": 0.2903,
        "Syrian Arab Republic": 0.2777,
        "Burkina Faso": 0.2777,
        "Sri Lanka": 0.2777,
        "Malawi": 0.2524,
        "Zambia": 0.2524,
        "Romania": 0.2398,
        "Chile": 0.2398,
        "Kazakhstan": 0.2398,
        "Chad": 0.2272,
        "Ecuador": 0.2272,
        "Guatemala": 0.2272,
        "Somalia": 0.2272,
        "Netherlands (the)": 0.2272,
        "Senegal": 0.2146,
        "Cambodia": 0.2146,
        "Zimbabwe": 0.2019,
        "Rwanda": 0.1767,
        "Guinea": 0.1767,
        "Burundi": 0.1767,
        "Benin": 0.1641,
        "Bolivia": 0.1515,
        "Tunisia": 0.1515,
        "Belgium": 0.1515,
        "Haiti": 0.1515,
        "South Sudan": 0.1388,
        "Cuba": 0.1388,
        "Czechia": 0.1388,
        "Dominican Republic": 0.1388,
        "Jordan": 0.1262,
        "Greece": 0.1262,
        "Sweden": 0.1262,
        "Portugal": 0.1262,
        "Azerbaijan": 0.1262,
        "Hungary": 0.1262,
        "Tajikistan": 0.1262,
        "United Arab Emirates": 0.1262,
        "Honduras": 0.1262,
        "Papua New Guinea": 0.1262,
        "Israel": 0.1136,
        "Togo": 0.1136,
        "Austria": 0.1136,
        "Belarus": 0.1136,
        "Switzerland": 0.1136,
        "Sierra Leone": 0.101,
        "Lao People's Democratic Republic": 0.101,
        "Serbia": 0.0884,
        "Libya": 0.0884,
        "Kyrgyzstan": 0.0884,
        "Nicaragua": 0.0884,
        "Bulgaria": 0.0884,
        "El Salvador": 0.0757,
        "Turkmenistan": 0.0757,
        "Denmark": 0.0757,
        "Finland": 0.0757,
        "Republic of the Congo": 0.0757,
        "Singapore": 0.0757,
        "Slovakia": 0.0757,
        "Norway": 0.0631,
        "Palestine, State of": 0.0631,
        "Costa Rica": 0.0631,
        "New Zealand": 0.0631,
        "Ireland": 0.0631,
        "Oman": 0.0631,
        "Liberia": 0.0631,
        "Central African Republic": 0.0631,
        "Mauritania": 0.0631,
        "Kuwait": 0.0631,
        "Panama": 0.0505,
        "Croatia": 0.0505,
        "Georgia": 0.0505,
        "Eritrea": 0.0379,
        "Moldova": 0.0379,
        "Puerto Rico": 0.0379,
        "Bosnia and Herzegovina": 0.0379,
        "Albania": 0.0379,
        "Armenia": 0.0379,
        "Lithuania": 0.0379,
        "Jamaica": 0.0379,
        "Qatar": 0.0379,
        "Namibia": 0.0379,
        "Gambia": 0.0379,
        "Botswana": 0.0379,
        "Gabon": 0.0252,
        "Lesotho": 0.0252,
        "Slovenia": 0.0252,
        "Republic of North Macedonia": 0.0252,
        "Latvia": 0.0252,
        "Guinea-Bissau": 0.0252,
        "Equatorial Guinea": 0.0252,
        "Bahrain": 0.0252,
        "Sao Tome and Principe": 0.0126,
        "Trinidad and Tobago": 0.0126,
        "Estonia": 0.0126,
        "Timor-Leste": 0.0126,
        "Mauritius": 0.0126,
        "Cyprus": 0.0126,
        "Eswatini": 0.0126,
        "Djibouti": 0.0126,
        "Fiji": 0.0126,
        "Comoros": 0.0126,
        "Guyana": 0.0126,
        "Bhutan": 0.0126,
        "Solomon Islands": 0.0126,
        "Montenegro": 0.0126,
        "Luxembourg": 0.0126,
        "Suriname": 0.0126,
        "Cabo Verde": 0.0126,
        "Malta": 0.0126,
        "Brunei Darussalam": 0.0126,
        "Belize": 0.0126,
        "Bahamas": 0.0126,
        "Maldives": 0.0126,
        "Iceland": 0.0126,
        "Vanuatu": 0.0126,
        "Barbados": 0.0126,
        "Samoa": 0.0126,
        "Saint Lucia": 0.0126,
        "Kiribati": 0.0126,
        "Micronesia": 0.0126,
        "Grenada": 0.0126,
        "Tonga": 0.0126,
        "Seychelles": 0.0126,
        "Antigua and Barbuda": 0.0126,
        "Andorra": 0.0126,
        "Dominica": 0.0126,
        "Saint Kitts and Nevis": 0.0126,
        "Marshall Islands": 0.0126,
        "Liechtenstein": 0.0126,
        "Monaco": 0.0126,
        "San Marino": 0.0126,
        "Palau": 0.0126,
        "Tuvalu": 0.0126,
        "Nauru": 0.0126,
        "Holy See": 0.0126,
    ]
    static let codes: [String: String] = [
        "Zimbabwe": "ZWE",
        "Zambia": "ZMB",
        "South Africa": "ZAF",
        "Yemen": "YEM",
        "Samoa": "WSM",
        "Wallis and Futuna": "WLF",
        "Vanuatu": "VUT",
        "Viet Nam": "VNM",
        "U.S. Virgin Islands": "VIR",
        "Virgin Islands": "VGB",
        "Venezuela": "VEN",
        "Saint Vincent and the Grenadines": "VCT",
        "Holy See": "VAT",
        "Uzbekistan": "UZB",
        "United States of America": "USA",
        "Uruguay": "URY",
        "United States Minor Outlying Islands": "UMI",
        "Ukraine": "UKR",
        "Uganda": "UGA",
        "Tanzania, United Republic of": "TZA",
        "Taiwan": "TWN",
        "Tuvalu": "TUV",
        "Turkey": "TUR",
        "Tunisia": "TUN",
        "Trinidad and Tobago": "TTO",
        "Tonga": "TON",
        "Timor-Leste": "TLS",
        "Turkmenistan": "TKM",
        "Tokelau": "TKL",
        "Tajikistan": "TJK",
        "Thailand": "THA",
        "Togo": "TGO",
        "Chad": "TCD",
        "Turks and Caicos Islands": "TCA",
        "Syrian Arab Republic": "SYR",
        "Seychelles": "SYC",
        "Sint Maarten": "SXM",
        "Eswatini": "SWZ",
        "Sweden": "SWE",
        "Slovenia": "SVN",
        "Slovakia": "SVK",
        "Suriname": "SUR",
        "Sao Tome and Principe": "STP",
        "South Sudan": "SSD",
        "Serbia": "SRB",
        "Saint Pierre and Miquelon": "SPM",
        "Somalia": "SOM",
        "San Marino": "SMR",
        "El Salvador": "SLV",
        "Sierra Leone": "SLE",
        "Solomon Islands": "SLB",
        "Svalbard and Jan Mayen": "SJM",
        "Saint Helena, Ascension and Tristan da Cunha": "SHN",
        "South Georgia and the South Sandwich Islands": "SGS",
        "Singapore": "SGP",
        "Senegal": "SEN",
        "Sudan": "SDN",
        "Saudi Arabia": "SAU",
        "Rwanda": "RWA",
        "Russia": "RUS",
        "Romania": "ROU",
        "Réunion": "REU",
        "Qatar": "QAT",
        "French Polynesia": "PYF",
        "Palestine": "PSE",
        "Paraguay": "PRY",
        "Portugal": "PRT",
        "North Korea": "PRK",
        "Puerto Rico": "PRI",
        "Poland": "POL",
        "Papua New Guinea": "PNG",
        "Palau": "PLW",
        "Philippines": "PHL",
        "Peru": "PER",
        "Pitcairn": "PCN",
        "Panama": "PAN",
        "Pakistan": "PAK",
        "Oman": "OMN",
        "New Zealand": "NZL",
        "Nauru": "NRU",
        "Nepal": "NPL",
        "Norway": "NOR",
        "Netherlands (the)": "NLD",
        "Niue": "NIU",
        "Nicaragua": "NIC",
        "Nigeria": "NGA",
        "Norfolk Island": "NFK",
        "Niger": "NER",
        "New Caledonia": "NCL",
        "Namibia": "NAM",
        "Mayotte": "MYT",
        "Malaysia": "MYS",
        "Malawi": "MWI",
        "Mauritius": "MUS",
        "Martinique": "MTQ",
        "Montserrat": "MSR",
        "Mauritania": "MRT",
        "Mozambique": "MOZ",
        "Northern Mariana Islands": "MNP",
        "Mongolia": "MNG",
        "Montenegro": "MNE",
        "Myanmar": "MMR",
        "Malta": "MLT",
        "Mali": "MLI",
        "Republic of North Macedonia": "MKD",
        "Marshall Islands": "MHL",
        "Mexico": "MEX",
        "Maldives": "MDV",
        "Madagascar": "MDG",
        "Moldova": "MDA",
        "Monaco": "MCO",
        "Morocco": "MAR",
        "Saint Martin": "MAF",
        "Macao": "MAC",
        "Latvia": "LVA",
        "Luxembourg": "LUX",
        "Lithuania": "LTU",
        "Lesotho": "LSO",
        "Sri Lanka": "LKA",
        "Liechtenstein": "LIE",
        "Saint Lucia": "LCA",
        "Libya": "LBY",
        "Liberia": "LBR",
        "Lebanon": "LBN",
        "Lao People's Democratic Republic": "LAO",
        "Kuwait": "KWT",
        "Korea": "KOR",
        "Saint Kitts and Nevis": "KNA",
        "Kiribati": "KIR",
        "Cambodia": "KHM",
        "Kyrgyzstan": "KGZ",
        "Kenya": "KEN",
        "Kazakhstan": "KAZ",
        "Japan": "JPN",
        "Jordan": "JOR",
        "Jersey": "JEY",
        "Jamaica": "JAM",
        "Italy": "ITA",
        "Israel": "ISR",
        "Iceland": "ISL",
        "Iraq": "IRQ",
        "Iran": "IRN",
        "Ireland": "IRL",
        "British Indian Ocean Territory": "IOT",
        "India": "IND",
        "Isle of Man": "IMN",
        "Indonesia": "IDN",
        "Hungary": "HUN",
        "Haiti": "HTI",
        "Croatia": "HRV",
        "Honduras": "HND",
        "Heard Island and McDonald Islands": "HMD",
        "Hong Kong": "HKG",
        "Guyana": "GUY",
        "Guam": "GUM",
        "French Guiana": "GUF",
        "Guatemala": "GTM",
        "Greenland": "GRL",
        "Grenada": "GRD",
        "Greece": "GRC",
        "Equatorial Guinea": "GNQ",
        "Guinea-Bissau": "GNB",
        "Gambia": "GMB",
        "Guadeloupe": "GLP",
        "Guinea": "GIN",
        "Gibraltar": "GIB",
        "Ghana": "GHA",
        "Guernsey": "GGY",
        "Georgia": "GEO",
        "United Kingdom of Great Britain and Northern Ireland (the)": "GBR",
        "Gabon": "GAB",
        "Micronesia": "FSM",
        "Faroe Islands": "FRO",
        "France": "FRA",
        "Falkland Islands": "FLK",
        "Fiji": "FJI",
        "Finland": "FIN",
        "Ethiopia": "ETH",
        "Estonia": "EST",
        "Spain": "ESP",
        "Western Sahara": "ESH",
        "Eritrea": "ERI",
        "Egypt": "EGY",
        "Ecuador": "ECU",
        "Algeria": "DZA",
        "Dominican Republic": "DOM",
        "Denmark": "DNK",
        "Dominica": "DMA",
        "Djibouti": "DJI",
        "Germany": "DEU",
        "Czechia": "CZE",
        "Cyprus": "CYP",
        "Cayman Islands": "CYM",
        "Christmas Island": "CXR",
        "Curaçao": "CUW",
        "Cuba": "CUB",
        "Costa Rica": "CRI",
        "Cabo Verde": "CPV",
        "Comoros": "COM",
        "Colombia": "COL",
        "Cook Islands (the)": "COK",
        "Republic of the Congo": "COG",
        "Democratic Republic of the Congo": "COD",
        "Cameroon": "CMR",
        "Côte d'Ivoire": "CIV",
        "China": "CHN",
        "Chile": "CHL",
        "Switzerland": "CHE",
        "Cocos (Keeling) Islands": "CCK",
        "Canada": "CAN",
        "Central African Republic": "CAF",
        "Botswana": "BWA",
        "Bouvet Island": "BVT",
        "Bhutan": "BTN",
        "Brunei Darussalam": "BRN",
        "Barbados": "BRB",
        "Brazil": "BRA",
        "Bolivia": "BOL",
        "Bermuda": "BMU",
        "Belize": "BLZ",
        "Belarus": "BLR",
        "Saint Barthélemy": "BLM",
        "Bosnia and Herzegovina": "BIH",
        "Bahamas": "BHS",
        "Bahrain": "BHR",
        "Bulgaria": "BGR",
        "Bangladesh": "BGD",
        "Burkina Faso": "BFA",
        "Bonaire, Sint Eustatius and Saba": "BES",
        "Benin": "BEN",
        "Belgium": "BEL",
        "Burundi": "BDI",
        "Azerbaijan": "AZE",
        "Austria": "AUT",
        "Australia": "AUS",
        "Antigua and Barbuda": "ATG",
        "French Southern Territories": "ATF",
        "Antarctica": "ATA",
        "American Samoa": "ASM",
        "Armenia": "ARM",
        "Argentina": "ARG",
        "United Arab Emirates": "ARE",
        "Andorra": "AND",
        "Albania": "ALB",
        "Åland Islands": "ALA",
        "Anguilla": "AIA",
        "Angola": "AGO",
        "Afghanistan": "AFG",
        "Aruba": "ABW"
    ]
    
    static let flags: [String: String] = [
        "Afghanistan": "🇦🇫",
        "Albania": "🇦🇱",
        "Algeria": "🇩🇿",
        "Andorra": "🇦🇩",
        "Angola": "🇦🇴",
        "Antigua and Barbuda": "🇦🇬",
        "Argentina": "🇦🇷",
        "Armenia": "🇦🇲",
        "Australia": "🇦🇺",
        "Austria": "🇦🇹",
        "Azerbaijan": "🇦🇿",
        "Bahamas": "🇧🇸",
        "Bahrain": "🇧🇭",
        "Bangladesh": "🇧🇩",
        "Barbados": "🇧🇧",
        "Belarus": "🇧🇾",
        "Belgium": "🇧🇪",
        "Belize": "🇧🇿",
        "Benin": "🇧🇯",
        "Bhutan": "🇧🇹",
        "Bolivia": "🇧🇴",
        "Bosnia and Herzegovina": "🇧🇦",
        "Botswana": "🇧🇼",
        "Brazil": "🇧🇷",
        "Brunei Darussalam": "🇧🇳",
        "Bulgaria": "🇧🇬",
        "Burkina Faso": "🇧🇫",
        "Burundi": "🇧🇮",
        "Cabo Verde": "🇨🇻",
        "Cambodia": "🇰🇭",
        "Cameroon": "🇨🇲",
        "Canada": "🇨🇦",
        "Central African Republic": "🇨🇫",
        "Chad": "🇹🇩",
        "Chile": "🇨🇱",
        "China": "🇨🇳",
        "Colombia": "🇨🇴",
        "Comoros": "🇰🇲",
        "Costa Rica": "🇨🇷",
        "Croatia": "🇭🇷",
        "Cuba": "🇨🇺",
        "Cyprus": "🇨🇾",
        "Czechia": "🇨🇿",
        "Côte d'Ivoire": "🇨🇮",
        "Democratic Republic of the Congo": "🇨🇩",
        "Denmark": "🇩🇰",
        "Djibouti": "🇩🇯",
        "Dominica": "🇩🇲",
        "Dominican Republic": "🇩🇴",
        "Ecuador": "🇪🇨",
        "Egypt": "🇪🇬",
        "El Salvador": "🇸🇻",
        "Equatorial Guinea": "🇬🇶",
        "Eritrea": "🇪🇷",
        "Estonia": "🇪🇪",
        "Eswatini": "🇸🇿",
        "Ethiopia": "🇪🇹",
        "Fiji": "🇫🇯",
        "Finland": "🇫🇮",
        "France": "🇫🇷",
        "Gabon": "🇬🇦",
        "Gambia": "🇬🇲",
        "Georgia": "🇬🇪",
        "Germany": "🇩🇪",
        "Ghana": "🇬🇭",
        "Greece": "🇬🇷",
        "Grenada": "🇬🇩",
        "Guatemala": "🇬🇹",
        "Guinea": "🇬🇳",
        "Guinea-Bissau": "🇬🇼",
        "Guyana": "🇬🇾",
        "Haiti": "🇭🇹",
        "Holy See": "🇻🇦",
        "Honduras": "🇭🇳",
        "Hungary": "🇭🇺",
        "Iceland": "🇮🇸",
        "India": "🇮🇳",
        "Indonesia": "🇮🇩",
        "Iran": "🇮🇷",
        "Iraq": "🇮🇶",
        "Ireland": "🇮🇪",
        "Israel": "🇮🇱",
        "Jamaica": "🇯🇲",
        "Japan": "🇯🇵",
        "Jordan": "🇯🇴",
        "Kazakhstan": "🇰🇿",
        "Kenya": "🇰🇪",
        "Kiribati": "🇰🇮",
        "Korea": "🇰🇷",
        "Kuwait": "🇰🇼",
        "Kyrgyzstan": "🇰🇬",
        "Lao People's Democratic Republic": "🇱🇦",
        "Latvia": "🇱🇻",
        "Lesotho": "🇱🇸",
        "Liberia": "🇱🇷",
        "Libya": "🇱🇾",
        "Liechtenstein": "🇱🇮",
        "Lithuania": "🇱🇹",
        "Luxembourg": "🇱🇺",
        "Madagascar": "🇲🇬",
        "Malawi": "🇲🇼",
        "Malaysia": "🇲🇾",
        "Maldives": "🇲🇻",
        "Mali": "🇲🇱",
        "Malta": "🇲🇹",
        "Marshall Islands": "🇲🇭",
        "Mauritania": "🇲🇷",
        "Mauritius": "🇲🇺",
        "Mexico": "🇲🇽",
        "Micronesia": "🇫🇲",
        "Moldova": "🇲🇩",
        "Monaco": "🇲🇨",
        "Montenegro": "🇲🇪",
        "Morocco": "🇲🇦",
        "Mozambique": "🇲🇿",
        "Myanmar": "🇲🇲",
        "Namibia": "🇳🇦",
        "Nauru": "🇳🇷",
        "Nepal": "🇳🇵",
        "Netherlands (the)": "🇳🇱",
        "New Zealand": "🇳🇿",
        "Nicaragua": "🇳🇮",
        "Niger": "🇳🇪",
        "Nigeria": "🇳🇬",
        "North Korea": "🇰🇵",
        "Norway": "🇳🇴",
        "Oman": "🇴🇲",
        "Pakistan": "🇵🇰",
        "Palau": "🇵🇼",
        "Palestine, State of": "🇵🇸",
        "Panama": "🇵🇦",
        "Papua New Guinea": "🇵🇬",
        "Peru": "🇵🇪",
        "Philippines": "🇵🇭",
        "Poland": "🇵🇱",
        "Portugal": "🇵🇹",
        "Puerto Rico": "🇵🇷",
        "Qatar": "🇶🇦",
        "Republic of North Macedonia": "🇲🇰",
        "Republic of the Congo": "🇨🇬",
        "Romania": "🇷🇴",
        "Russisa": "🇷🇺",  // typo in weights key — consider fixing to "Russia"
        "Rwanda": "🇷🇼",
        "Saint Kitts and Nevis": "🇰🇳",
        "Saint Lucia": "🇱🇨",
        "Samoa": "🇼🇸",
        "San Marino": "🇸🇲",
        "Sao Tome and Principe": "🇸🇹",
        "Saudi Arabia": "🇸🇦",
        "Senegal": "🇸🇳",
        "Serbia": "🇷🇸",
        "Seychelles": "🇸🇨",
        "Sierra Leone": "🇸🇱",
        "Singapore": "🇸🇬",
        "Slovakia": "🇸🇰",
        "Slovenia": "🇸🇮",
        "Solomon Islands": "🇸🇧",
        "Somalia": "🇸🇴",
        "South Africa": "🇿🇦",
        "South Sudan": "🇸🇸",
        "Spain": "🇪🇸",
        "Sri Lanka": "🇱🇰",
        "Sudan": "🇸🇩",
        "Suriname": "🇸🇷",
        "Sweden": "🇸🇪",
        "Switzerland": "🇨🇭",
        "Syrian Arab Republic": "🇸🇾",
        "Taiwan": "🇹🇼",
        "Tajikistan": "🇹🇯",
        "Tanzania, United Republic of": "🇹🇿",
        "Thailand": "🇹🇭",
        "Timor-Leste": "🇹🇱",
        "Togo": "🇹🇬",
        "Tonga": "🇹🇴",
        "Trinidad and Tobago": "🇹🇹",
        "Tunisia": "🇹🇳",
        "Turkey": "🇹🇷",
        "Turkmenistan": "🇹🇲",
        "Tuvalu": "🇹🇻",
        "Uganda": "🇺🇬",
        "Ukraine": "🇺🇦",
        "United Arab Emirates": "🇦🇪",
        "United Kingdom of Great Britain and Northern Ireland (the)": "🇬🇧",
        "United States of America": "🇺🇸",
        "Uzbekistan": "🇺🇿",
        "Vanuatu": "🇻🇺",
        "Venezuela": "🇻🇪",
        "Viet Nam": "🇻🇳",
        "Yemen": "🇾🇪",
        "Zambia": "🇿🇲",
        "Zimbabwe": "🇿🇼",
    ]


    func getCountry() -> String {
        let roll = Double.random(in: 0..<100)
        var total = 0.0

        let sortedWeights = countryInfo.weights.sorted { $0.key < $1.key }

        for (country, weight) in sortedWeights {
            total += weight
            if total >= roll {
                return country
            }
        }
        return "Bolivia"
    }
    func getCode(country: String) -> String{
        return countryInfo.codes[country] ?? "BOL"
    }
    
    func getFlag(country: String) -> String{
        return countryInfo.flags[country] ?? "🇧🇴"
    }


}
